### PR TITLE
use @esri/arcgis-rest-request instead of the JSAPI

### LINKED ISSUE #1: possibility to leverage the typings in @esri/arcgis-rest-js?
hey @mvdbster :wave:! just saw this very cool project!

i only took a quick snoop through the code, but it got me thinking that it sure would be great if you could reuse all the typings we've been putting together in [`@esri/arcgis-rest-common-types`](https://github.com/Esri/arcgis-rest-js/tree/master/packages/arcgis-rest-common-types). not sure if/how that'd work in a vanilla JS project though...

### PR DESCRIPTION
**Pull request by jgravois**
resolves #1 	

~~i'm not familiar with jest so i didn't spend much time trying to figure out how to intercept calls to `request`, but these tweaks definitely worked in my manual browser testing.~~

```html
<script src="arcgoose.js"></script>
```
```js
async function go() {
  const url = `http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer`;
  const connection = await arcgoose.default.connect({ url });
  const States = await arcgoose.default.model(connection.layers.states, { STATE_NAME: String });
  const state = await States.findOne({ STATE_NAME: 'Alaska' }).exec();
  // >> {attributes: { STATE_NAME: 'Alaska' }, geometry: null, centroid: null}
}

go();
```

### CODE REVIEW

**Comment by mvdbster** [comment]
@jgravois sorry, I somehow missed this. So awesome that you did this. I will have a look at it now...

**Comment by mvdbster** [comment]
I will need to add the authentication session before I can test it in Urban (including passing the session object from Urban whenever doing requests). Due to some time pressure, I will have to do this a couple of weeks from now before I can test and merge...

**Comment by jgravois** [comment]
no worries!

**Comment by jgravois** [comment]
@mvdbster i had a little free time this afternoon so I upgraded to `v2.x` and fixed the tests.

Screen Shot 2019-05-14 at 3 37 39 PM

**Pull request merged**
